# Generated by Django 5.1.3 on 2024-11-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='route',
            field=models.CharField(choices=[('Route1', 'Route1'), ('Route2', 'Route2'), ('Route3', 'Route3'), ('Route4', 'Route4'), ('Route5', 'Route5'), ('Route6', 'Route6'), ('Route7', 'Route7'), ('Route8', 'Route8')], default='TBL', max_length=10),
        ),
    ]
