# Generated by Django 5.1.3 on 2024-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_wasterequest_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequest',
            name='route',
            field=models.CharField(choices=[('Route1', 'Route1'), ('Route2', 'Route2'), ('Route3', 'Route3'), ('Route4', 'Route4'), ('Route5', 'Route5'), ('Route6', 'Route6')], default='TBL', max_length=10),
        ),
    ]
